source 'https://rubygems.org'
ruby '2.7.4'
gem 'rubocop', '~> 0.57.2'
# gem 'rspec'
# gem 'dotenv'
# gem 'http'
# gem 'nokogiri'
# gem 'pry'
# gem 'launchy'
gem 'csv'
# gem 'json'
gem 'puma'
gem 'sinatra'
gem 'rack'
gem "shotgun", "~> 0.9.2"
